version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: poetry run uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .relia-data:/app/.relia-data
      - .relia-playbooks:/app/.relia-playbooks
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - RELIA_ENV=dev
      - RELIA_ENFORCE_HTTPS=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Security settings
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

