apiVersion: apps/v1
kind: Deployment
metadata:
  name: relia-backend
  labels:
    app: relia
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relia
      component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: relia
        component: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: backend
        image: ${CONTAINER_REGISTRY}/relia-backend:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: RELIA_ENV
          value: "prod"
        - name: RELIA_ENFORCE_HTTPS
          value: "true"
        - name: RELIA_SECURE_COOKIES
          value: "true"
        - name: RELIA_HSTS_ENABLED
          value: "true"
        - name: RELIA_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: relia-secrets
              key: jwt-secret
        - name: RELIA_CSRF_SECRET
          valueFrom:
            secretKeyRef:
              name: relia-secrets
              key: csrf-secret
        - name: RELIA_BASE_URL
          value: "https://${DOMAIN}"
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: relia-data
          mountPath: /app/.relia-data
        - name: relia-playbooks
          mountPath: /app/.relia-playbooks
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      volumes:
      - name: relia-data
        persistentVolumeClaim:
          claimName: relia-data-pvc
      - name: relia-playbooks
        persistentVolumeClaim:
          claimName: relia-playbooks-pvc
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relia-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relia-playbooks-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: relia-secrets
type: Opaque
data:
  # These are placeholder values - replace with real base64-encoded secrets
  jwt-secret: UmVwbGFjZVRoaXNXaXRoQVNlY3VyZVNlY3JldA==
  csrf-secret: UmVwbGFjZVRoaXNXaXRoQW5vdGhlclNlY3VyZVNlY3JldA==